LangCS={
	title:"인증서 선택창",
	vCertStat1024:"유효한 구인증서 입니다.",
	eCertStat1024:"만료된 구인증서 입니다.",
	uCertStat1024:"갱신기간 내 구인증서입니다.",
	vCertStat2048:"유효한 신인증서 입니다.",
	eCertStat2048:"만료된 신인증서 입니다.",
	uCertStat2048:"갱신기간 내 신인증서입니다.",
	needSelectCert:'선택한 인증서가 없습니다.',
	CertStorage:'저장매체',
	removableDisk:'이동식디스크',
	smartCard:'스마트 카드',
	SecureToken:'보안토큰',
	HardDisk:'하드디스크',
	Phone:'휴대폰',
	CertStat:'상태',
	CertOwner:'소유자명',
	CertIssuer:'발급기관',
	CertUsage:'구분',
	CertExDatae:'만료일',
	CertSearch:"인증서가 없을 경우 \'찾아보기\' 버튼을 클릭하세요.",
	CertPassword:'인증서 비밀번호',
	notCorrect:'패스워드가 일치하지 않습니다. \n 다시확인 후 시도해 주세요.',
	notCorrectPin:'Pin 번호가 올바르지 않습니다.\n 확인 후 다시 시도해 주세요.',
	notSelected:'선택한 인증서가 없습니다.',
	notInput:'패스워드 입력 후 다시 시도해 주세요.',
	notConnect:'해당 저장매체에는 인증서가 존재하지 않습니다.\n 다른 저장매체를 선택하시거나 매체 연결 후 다시 시도해 주세요.',
	notExits:'해당 저장매체에는 인증서가 존재하지 않습니다.\n 다른 저장매체를 선택하시거나 매체 연결 후 다시 시도해 주세요.',
	OKStat:'확인',
	CancelStat:'취소',
	FindStat:'찾아보기',
	ViewVerify:'보기/검증',
	alertMsg001:"선택한 인증서가 없습니다.",
	alertMsg002:"패스워드를 입력해 주세요.",
	alertMsg003:"비밀번호가 틀렸습니다. 다시 확인 후 시도하세요.",
	alertMsg004:"해당 저장매체에는 인증서가 존재하지 않습니다.\n 다른 저장매체를 선택하시거나 매체 연결 후 다시 시도해 주세요.",
	alertMsg005:"Pin 번호가 올바르지 않습니다.\n 확인 후 다시 시도해 주세요.",
	alertMsg006:"해당 서비스 프로그램이 설치 되지 않았습니다.\n 팝업 페이지지에서 해당 프로그램 설치 후 다시 시도하세요.",
	alertMsg007:"해당 서비스는 접속하신 브라우저를 지원하지 않습니다.\n인터넷 익스플러 브라우저로 다시 시도하세요.",
	alertMsg008:"해당 서비스 모듈이 업데이트 되었습니다. \n 업데이트 후 시도하세요.",
	alertMsg009:"고객님 OS는 해당 서비스 프로그램이 지원되지 않는 OS 입니다.\n Windows에서 다시 시도하세요.",
	alertMsg010:"해당 서비스를 지원하지 않습니다.\n 웹관리자에게 문의하세요.",
	alertMsg011:"보안토큰의 비밀번호가 틀렸습니다. 다시 확인 후 시도하세요."
}
