LangR = {
			tab01:"일반",
			tab02:"자세히",
			certState : "상태",
			certState001 : "올바른 인증서 입니다.",
			certState002 : "유효하지 않은 인증서 입니다.",
			certState003 : "검증 중...",
			certState : "상태",
			CertGF01 : "인증서 정보",				
			CertGF02 : "인증서 용도",
			CertGF03:" * 자세한 정보는 인증기관의 설명을 참조하십시오",
			CertGF04:" 발급 대상 : ",
			CertGF05 :" 발급자 : ",
			CertGF06 : " 유효 기간 : ",
			CertGF07 : " 구    분 : ",
			CertGF08 : " 상   태 : ",
			CertGF09 :"인증서 검증",
			CertGF10:"사용자 알림",
			certFieldName : [
			         		"버전",
			         		"일련번호",
			         		"서명알고리즘",
			         		"발급자",
			         		"유효기간\(시작\)",
			         		"유효기간\(끝\)",
			         		"주체",
			         		"공개키",
			         		"기관키 식별자",
			         		"주체키식별자",
			         		"키사용",
			         		"인증서정책",
			         		"주체대체이름",
			         		"CRL배포지점",
			         		"기관정보지점",
			         		"손도장알고리즘",
			         		"손도장"		
			         ],
			 strConfirm : "확인",
			 alertMsg : "알림 메시지",
			 CertDF01:"필드",
			 CertDF02:"내용"
	}