/* Sequence 저장테이블 */

/* 공통분류코드 */

/* 공통코드 */
/*INSERT INTO COMTCCMMNCODE(CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID,LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC', 'CTA001', '평가지표', '평가지표', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');*/

/* 공통상세코드 */
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI001', '1-1. 민원행정 및 제도개선 계획수립의 적합성', '민원행정 및 제도개선 계획수립의 적합성', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI002', '1-2. 기관장의 의지 및 관심도', '기관장의 의지 및 관심도', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI003', '1-3. 민원 우수 인센티브 제공', '민원 우수 인센티브 제공', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI004', '1-4. 민원행정 수행기반', '민원행정 수행기반', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI005', '2-1. 민원정보 제공 및 민원법령 운영', '민원정보 제공 및 민원법령 운영', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI006', '2-2. 민원처리상황 확인·점검', '민원처리상황 확인·점검', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI007', '2-3. 민원행정 및 제도개선', '민원행정 및 제도개선', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI008', '민원행정 활동 - 가점', '가점', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI009', '민원행정 활동 - 감점', '감점', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');

/* 그룹정보 */
DELETE FROM `comtnauthorgroupinfo`;
INSERT INTO `comtnauthorgroupinfo` (`GROUP_ID`, `GROUP_NM`, `GROUP_CREAT_DE`, `GROUP_DC`) VALUES ('GROUP_00000000000001', '기관담당자', CURRENT_TIMESTAMP, '기관담당자');
INSERT INTO `comtnauthorgroupinfo` (`GROUP_ID`, `GROUP_NM`, `GROUP_CREAT_DE`, `GROUP_DC`) VALUES ('GROUP_00000000000002', '평가위원', CURRENT_TIMESTAMP, '평가위원');
INSERT INTO `comtnauthorgroupinfo` (`GROUP_ID`, `GROUP_NM`, `GROUP_CREAT_DE`, `GROUP_DC`) VALUES ('GROUP_00000000000003', '관리자', CURRENT_TIMESTAMP, '관리자');
