/* Sequence 저장테이블 */

/* 공통분류코드 */

/* 공통코드 */
INSERT INTO COMTCCMMNCODE(CL_CODE, CODE_ID, CODE_ID_NM, CODE_ID_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID,LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('EFC', 'CTA001', '평가지표', '평가지표', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');

/* 공통상세코드 */
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI001', '민원행정 및 제도개선 계획수립의 적합성', '민원행정 및 제도개선 계획수립의 적합성', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI002', '기관장의 의지 및 관심도', '기관장의 의지 및 관심도', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI003', '민원 우수 인센티브 제공', '민원 우수 인센티브 제공', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI004', '민원행정 수행기반', '민원행정 수행기반', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI005', '민원정보 제공 및 민원법령 운영', '민원정보 제공 및 민원법령 운영', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI006', '민원처리상황 확인·점검', '민원처리상황 확인·점검', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI007', '민원행정 및 제도개선', '민원행정 및 제도개선', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI008', '처리기간 준수율', '처리기간 준수율', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
INSERT INTO COMTCCMMNDETAILCODE(CODE_ID, CODE, CODE_NM, CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('CTA001', 'CAI009', '지자체포털민원 만족도', '지자체포털민원 만족도', 'Y', SYSDATE(), 'SYSTEM', SYSDATE(), 'SYSTEM');
